# Generated by Django 4.1 on 2022-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField(max_length=100)),
                ("dataDeNascimento", models.DateField()),
                ("cpf", models.TextField(blank=True, max_length=11)),
                ("curriculo", models.FileField(blank=True, upload_to="")),
            ],
        ),
    ]
