# Generated by Django 4.1 on 2022-09-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="dataDeNascimento",
            field=models.DateField(blank=True),
        ),
    ]
